import { Noticia_Text } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

const noticia = Noticia_Text({
  subsets: ["latin"],
  display: 'swap',
  variable: "--noticia-text",
  weight: ['400', '700']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${noticia.variable}`}>
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: `
:root{
  --bg:#fff;
  --bg-soft:#f5f5f5;
  --text:#111;
  --muted:#6b7280;
  --border:#e5e7eb;
  --radius:4px;
  --max:1120px;
}
*{box-sizing:border-box}
html,body{height:100%}
body{
  margin:0;
  font-family:"Noticia Text", serif;
  background:var(--bg);
  color:var(--text);
  line-height:1.55;
}
a{color:inherit;text-decoration:none}
a:hover{text-decoration:underline;color:#4b5563}
.container{
  width:100%;
  max-width:var(--max);
  margin:0 auto;
  padding:0 16px;
}
.site-header{
  background:#0b0b0b;
  color:#f3f4f6;
}
.nav-row{
  display:flex;
  align-items:center;
  gap:14px;
  padding:14px 0;
  flex-wrap:wrap;
}
.brand{
  font-weight:700;
  letter-spacing:.4px;
  white-space:nowrap;
}
.nav-toggle{display:none}
.nav-toggle-btn{
  display:none;
  margin-left:auto;
  cursor:pointer;
  user-select:none;
  font-size:20px;
  padding:6px 10px;
  border:1px solid rgba(255,255,255,.18);
  border-radius:var(--radius);
}
.nav-right{
  display:flex;
  align-items:center;
  gap:14px;
  margin-left:auto;
}
.nav{
  display:flex;
  gap:12px;
  flex-wrap:wrap;
}
.nav-link{
  color:#f3f4f6;
  opacity:.95;
  padding:6px 8px;
  border-radius:var(--radius);
}
.nav-link:hover{opacity:1;background:rgba(255,255,255,.08);text-decoration:none}
.nav-link.active{background:rgba(255,255,255,.12)}
.nav-search{
  display:flex;
  gap:8px;
  align-items:center;
}
.nav-search input{
  width:220px;
  max-width:100%;
  padding:8px 10px;
  border-radius:var(--radius);
  border:1px solid rgba(255,255,255,.18);
  background:#111;
  color:#f3f4f6;
  outline:none;
}
.nav-search input::placeholder{color:rgba(243,244,246,.65)}
.nav-search button{
  padding:8px 10px;
  border-radius:var(--radius);
  border:1px solid rgba(255,255,255,.18);
  background:#111;
  color:#f3f4f6;
  cursor:pointer;
}
.nav-search button:hover{background:#1a1a1a}
main{padding:22px 0}

/* Responsive navbar (critical) */
@media (max-width: 760px){
  .nav-toggle-btn{display:inline-flex}
  .nav-right{display:none; width:100%; margin-left:0; flex-direction:column; align-items:stretch; gap:10px}
  .nav{flex-direction:column; gap:6px}
  .nav-search{width:100%}
  .nav-search input{flex:1; width:100%}
  .nav-toggle:checked ~ .nav-right{display:flex}
}
            `,
          }}
        />
      </head>
      <body className={`antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
